services:
  # Main Streamlit application
  pint-of-science:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pint-of-science-app
    hostname: pintbr
    restart: unless-stopped
    ports:
      - "8502:8501"
    env_file:
      - .env
    networks:
      - proxy

    volumes:
      # Database persistence
      - ./data:/app/data
      # Static files (logo, etc.)
      - ./static:/app/static

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Security settings
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1024M

networks:
  proxy:
    external: true
